#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:47:04 2022

@author: yabsera
"""

# -*- coding: utf-8 -*-
"""
Spyder Editor
2d array
This is a temporary script file.
"""

nested_lst=[[1,2,3], [4,5,6], [7,8,9]]
#Type your answer here.
ans_1=nested_lst[1][1]

print(ans_1)