#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:28:10 2022
split as smpicolom as parameter
@author: yabsera
"""

str="101:102:103:201:202"
#Type your code here.

lst=str.split(":")

print(lst)

