#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 11 18:22:38 2022
adding word using map
@author: yabsera
"""

#Type your answer here.

lst1=["Jane", "Lee", "Will", "Brie"]

lst2=list(map(lambda x:"Hello "+x,lst1))

print(lst2)

