#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 26 12:47:29 2022

@author: yabsera
"""

def add(arr,word,num):
    if type(arr)!=dict:
        return "Enter the correct dict"
    arr[word]=num
    return arr
