#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:49:42 2022
accessing elements in 2d array
@author: yabsera
"""

nested_lst = [["Hat", "Glove", "Goggle"], ["Button", "Zipper", "Hook"]]
#Type your code here.

ans_1=nested_lst[1][1][0]


print(ans_1)

