#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 21 12:01:15 2022
https://hackersandslackers.com/scraping-urls-with-beautifulsoup/

@author: yabsera
"""

from requests import get
from bs4 import BeautifulSoup
url="https://www.rottentomatoes.com/m/prey_2022"
tomoato=get(url)
soupt=BeautifulSoup(tomoato.text,'html.parser')
count=0
p=soupt.find('p', class_="what-to-know__section-body").get_text()
print(p)