#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 29 12:19:35 2022
Create a function that takes an array of numbers and return "Boom!" 
 if the digit 7 appears in the array. Otherwise, return "there is no 7 in the array".

@author: yabsera
"""

def boom(arr):
    try: 
        if arr.index(7)!=-1:
            return "Boom"
    except: 
        return "no  boom"
print (boom(["7",3,7]))
            
    