#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug  9 17:06:05 2022
Write a for loop using an if statement, 
that appends each number to the new list if it's positive.
@author: yabsera
"""

lst1=[111, 32, -9, -45, -17, 9, 85, -10]
lst2=[]
#Type your answer here.
for i in lst1:
    if(i>0):
        lst2.append(i)


print(lst2)

