#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:53:49 2022
Print the values of the "roads" key from the nested dictionary.
@author: yabsera
"""

nested_dict = {"Dakar":{"weather":"sunny", "roads":"dry"}}
#Type your answer here.

ans_1=nested_dict["Dakar"]["roads"]


print(ans_1)


