#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 29 13:01:59 2022
Create a function that takes a variable number of arguments. 
each argument representing the number of items in a group. 
The function should return the number of permutations (combinations) of choices you would have if you selected one item from each group.
@author: yabsera
"""

def comb(*num):
    com=1
    for i in num:
        com*=i
    return com
print(comb(4,7,3))