#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 19 18:03:58 2022

@author: yabsera
"""

from requests import get
url ="https://appsgeyser.com/blog/how-to-make-money-online-with-telegram-channel/"
webPage=get(url)
allcon=webPage.text
page=allcon
print(len(page))
count=0
num=0
po=0
nex=0
while(num<len(page)):
    if(page[num]=="<"):
        po=num+1
        if(po=="p"):
            count+=1
    num+=1
   
print(count)
