import pandas as pd

df = pd.read_csv("csvData.csv")
print("=============================================================")
print("====================Info of 2022=============================")
print("=============================================================")
print("Highest number of population",df["pop2022"].max())
print("The mean of population:",round(df["pop2022"].mean(),2))
print("The total of population:",round(df["pop2022"].sum(),2))
print("The Range of population:",round(df["pop2022"].max()-df["pop2022"].min(),2))
print("=============================================================")
print("====================Rank of 2021=============================")
print("=============================================================")
print("Hightest rank of 2021\n",df["country"].head())
print("Lowest rank of 2021\n",df["country"].tail())
print("=============================================================")
print("====================Rank of 2020=============================")
print("=============================================================")
print("Hightest rank of 2020\n",df["country"].head())
print("Lowest rank of 2020\n",df["country"].tail())
print("=============================================================")
print("=============================================================")
print(df.isany("Ethiopia"))
