#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 16 11:43:00 2022

@author: yabsera
"""
class Jets:


    def __init__(self, name, country):
        self.name = name
        self.origin = country
        
        
        
first_item = Jets("F16", "USA")


a=first_item.name
print(a)
