#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 23 11:32:00 2022

@author: yabsera
"""

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
class Instagrambot:
    def __init__(self,username,password):
        self.username=username
        self.password=password
        self.driver=webdriver.Firefox(executable_path="./geckodriver")
    def closebrowser(self):
        self.driver.close()
    def login(self):
        driver=self.driver
        driver.get("https://www.google.com/")
test=Instagrambot("yabsera","life13579")