#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug  9 17:14:12 2022
Write a for loop which appends 
the type of each element in the first list to the second list
@author: yabsera
"""

lst1=[3.14, 66, "Teddy Bear", True, [], {}]
lst2=[]
#Type your answer here.
for i in lst1:
    lst2.append(type(i))


print(lst2)
