#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 13 12:26:38 2022

@author: yabsera
"""
import requests
num=int(input('Enter number: '))
i=0
i=num+((num*10)+num)+((num*100)+(num*10)+num)
print('I is: ',i)
