#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:22:23 2022
join list with
@author: yabsera
"""

lst=['Everything', 'has', 'beauty,', 'but', 'not', 'everyone', 'can', 'see.']
#Type your code here.

str=" ".join(lst)

print(str)
