#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:25:21 2022
join with newline
@author: yabsera
"""

poem_lst=["Not enjoyment, and not sorrow,", "Is our destined end or way;", "But to act, that each tomorrow", "Find us farther than today."]

#Type your code here.

poem_str="\n".join(poem_lst)


print(poem_str)
