#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:24:11 2022
joined with comma
@author: yabsera
"""


economic_growth={"India": 7.0, "Cambodia": 7, "Tanzania": 6.9, "Bangladesh": 6.6, "Senegal": 6.6}
#Type your code here.

str=",".join(economic_growth)


print(str)


