#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  7 17:01:33 2022

@author: yabsera
"""
from requests import get
from bs4 import BeautifulSoup


alajurl="https://www.aljazeera.com/africa/"
alaj=get(alajurl).content
alajnews=BeautifulSoup(alaj,'html.parser')
alajnews=alajnews.find_all("a",class_="u-clickable-card__link").text
print(alajnews)