#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 17:05:25 2022
Write a function which takes two arguments:
a and b and returns the multiplication of them:
a*b. Assign it to a variable named: f.
@author: yabsera
"""


#Type your answer here.

i,j=5,10

f=lambda a,b:a*b


print(f(i, j))

