#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 17:03:18 2022
Write a lambda function which takes z as a parameter and returns z*11

Assign it to variable named: f.
@author: yabsera
"""

#Type your answer here.

i=9

f=lambda z:z*11

print(f(i))

