#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 26 11:44:31 2022

@author: yabsera
"""

def lessthan100(a,b):
    if (a+b)<100:
        return True
    return False
print(lessthan100(23,50))