#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 15 14:58:35 2022

@author: yabsera
"""
from math import radians, cos, sin, asin, sqrt
from requests import get
import json
from pprint import pprint

def place(log1,lat1,log2,lat2):
    lat1=radians(lat1)
    lat2=radians(lat2)
    log1=radians(log1)
    log2=radians(log2)
    dlong=log2-log1
    dlat=lat2-lat1
    a = (sin(dlat/2)**2) + (cos(lat1) * cos(lat2) * (sin(dlong/2)**2))
    r=2 * asin(sqrt(a))
    c=6371
    return r*c

wea='https://apex.oracle.com/pls/apex/raspberrypi/weatherstation/getlatestmeasurements/'
sat='https://apex.oracle.com/pls/apex/raspberrypi/weatherstation/getallstations'
my_lat=38.7217115
my_log=8.9848969
all_stat=get(sat).json()['items']
def closest():
    for x in all_stat:
        s=20036
        lon=x['weather_stn_long']
        lat=x['weather_stn_lat']
        d=place(my_log,my_lat,lon,lat)
        if d<s:
            s=d
            c=x['weather_stn_id']
    return c
c=closest()
c=wea+str(c)
print(c)
c=get(c).json()['items']
pprint(c)
            
            
            
            
            
            