#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug  8 16:41:05 2022

@author: yabsera
"""
word="SAS"
letter=list()
print(letter)
for i in word:
    letter.append(i)
reword=letter
print("reword is ",reword)
letter.reverse()
print("letter is ",letter)
if(letter==reword):
    print(True)
else:
    print(False)

