#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 11 18:02:36 2022
pop last item
@author: yabsera
"""

lst=[11, 100, 99, 1000, 999]

#Type your answer here.

popped_item=lst.pop()
 
print(popped_item)
print(lst)

