#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:55:44 2022
Print the first element of the weather for Tokyo.
@author: yabsera
"""

nested_dict = {"Tokyo": {"weather":["sunny", "cloudy"], "roads":"dry"}, "Dakar": {"weather":["foggy","windy"], "roads": "sandy"}}
#Type your answer here.

ans_1=nested_dict["Tokyo"]["weather"][0]


print(ans_1)

