#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 16 13:12:44 2022
quantity
@author: yabsera
"""



class Jets:
    model = None
    country = 0

    def __init__(self, name, country,quantity):
        self.name = name
        self.origin = country
        self.quantity=quantity


first_item=Jets("F14","USA",87)
second_item=Jets("Mirage2000","France",35)

total=first_item.quantity+second_item.quantity
print(total)

