#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 23 14:55:21 2022

@author: yabsera
"""

import random
book=1000000
word=""
i=0
while i<book:
    k=random.randint(1,7)
    i+=1
    while k>0:
        j=random.randint(65,90)
        word+=chr(j)
        k-=1
    word+=" "
print(word)