#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 19 16:57:16 2022

@author: yabsera
"""
import re
from requests import get
import json
from pprint import pprint
regex=re.compile(r'<[^>]+>')
url='https://appsgeyser.com/blog/how-to-make-money-online-with-telegram-channel/'
test=get(url)
love=test.text
test=love.split(' ')
count=0
for x in test:
    j=0
    while(j<len(x)):
        if(x[j]=="<" and x[j]==">" and x[j]=="p"):
            j+=1
            count+=1
        else:
            j+=1
    
print("paragrah count is",count)
