#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:30:10 2022
split as ";" as parameter and print last element
@author: yabsera
"""

str="Arsenal:0-Chelsea:1;Barcelona:2-Bayern Munich:2"
#Type your code here.

lst=str.split(";")
ans_1=lst[len(lst)-1]

print(ans_1)


