#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 10 16:27:04 2022
split with space as parameter
@author: yabsera
"""

#Type your answer here.
str="Hello World!"
lst=str.split(" ")
 
print(lst)

