#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 11 18:20:10 2022
square number using map
@author: yabsera
"""

#Type your answer here.

lst1=[10, 20, 30, 40, 50, 60]

lst2=list(map(lambda x:x*x,lst1))

print(lst2)
