#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug  9 17:03:52 2022

@author: yabsera
"""

lst1=[3, 7, 6, 8, 9, 11, 15, 25]
lst2=[]
#Type your answer here.
for i in lst1:
    lst2.append(i*i)


print(lst2)