#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  2 15:26:57 2022

@author: yabsera
"""

def string(str):
    nstr=str.split()
    newstr=""
    for i in nstr:
        newstr+=i
        if(i[len(i)-1]=="."):
            newstr+="\n"
        else:
            newstr+=" "
    return newstr
print(string("xcvlkxvhlkx dfvslkv.     ssldkfls soiild. sodlksd      sdlsjdfsf.djflsd sdfklsdjflksdn sdljflskdjfl sdkls"))