#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 12 13:27:10 2022

@author: yabsera
"""

import urllib.request
fhand = urllib.request.urlopen('http://www.alanwood.net/unicode/ethiopic.html')
for line in fhand:
    print(type(line.decode().strip()))