#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 19 16:33:33 2022

@author: yabsera
"""

from requests import get
import json
from pprint import pprint
url='https://random-data-api.com/api/'
test=get(url)
pprint(test)
 
