#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  6 13:06:51 2022

@author: yabsera
"""
import random
import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
class Myroot(BoxLayout):
    def __init__(self):
        super(Myroot,self).__init__()
    def number(self):
        self.r1.text=str(random.randint(0,6))
class News(App):
    def build(self):
        return Myroot()
  
check=News()
check.run()
