#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug  8 16:41:05 2022

@author: yabsera
"""
word=input("Enter string: ")
letter=list()
print(letter)
for i in word:
    letter.append(i)
y=len(letter)
reword=list()
print("the length is ",y)
while( 0 < y):
    y-=1
    reword.append(letter[y])
    
print("the list in reverse: ",reword)
print("the list in letter: ",letter)
print("the word is palindrome ",reword==letter)