#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 15 14:22:29 2022

@author: yabsera
"""
from requests import get
import json
from pprint import pprint
url='https://apex.oracle.com/pls/apex/raspberrypi/weatherstation/getlatestmeasurements/255541'
sation=get(url).json()['items']
pprint(sation)